services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: ecostudent-app
        container_name: ecostudent-app
        restart: unless-stopped
        ports:
            - "80:80"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - ecostudent-network
        # No depends_on since we use external DB

networks:
    ecostudent-network:
        driver: bridge
